#!/usr/bin/env bash

set -u
set -x
set -e

git clone https://github.com/mauriciojost/mavarduino.git
mv mavarduino .mavarduino
.mavarduino/create_links

mkdir libs
cd libs
git clone https://github.com/mauriciojost/log4ino.git
